@baseUrl = http://localhost:5271

###Cadastra Contato
# @name cadastrarContato
POST {{baseUrl}}/api/contatos
Content-Type: application/json

{
    "nome": "Junior Testes",
    "email": "teste-{{$guid}}@academiadoprogramador.net",
    "telefone": "(49) 99999-9999",
    "cargo": "Analista de Testes",
    "empresa": "NDD"
}

### contato ID
@contatoId = {{cadastrarContato.response.body.$.id}}

### Listar Contatos
GET {{baseUrl}}/api/contatos

### Selecionar por Id
GET  {{baseUrl}}/api/contatos/{{contatoId}}